// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5lweTY8XpatalR0knkkSHfXrVtJDJy4c',
    appId: '1:161030257652:android:5006b28d7bb4e9b20557a1',
    messagingSenderId: '161030257652',
    projectId: 'sastastay-1d420',
    storageBucket: 'sastastay-1d420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGDPBsI1AOA5bxZMOLs1u_rN_wz9UQKU',
    appId: '1:161030257652:ios:dec53018c8eec51f0557a1',
    messagingSenderId: '161030257652',
    projectId: 'sastastay-1d420',
    storageBucket: 'sastastay-1d420.firebasestorage.app',
    androidClientId: '161030257652-asleoefo2bop372c04dblmhfdampdvtv.apps.googleusercontent.com',
    iosClientId: '161030257652-jknev8gmhmt4i8vc4l6un6alsof446jo.apps.googleusercontent.com',
    iosBundleId: 'com.sastastays.dealer',
  );

}